####################################### Services
services:
  service-loki:
    image: ahmettoguz/loki:3.4
    container_name: container-loki
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./config.yml:/etc/loki/config.yml
      - volume-loki:/loki
    networks:
      - network-monitor
    user: root
    restart: ${RESTART_POLICY}
    # ports:
    #   - "3100:3100"

####################################### Networks
networks:
  network-monitor:
    external: true

####################################### Volumes
volumes:
  volume-loki:
    name: volume-loki
